# Spring 开头的相关配置
spring:
  application:
    name: nacos # 应用名称
  datasource:
    platform: mysql

# Nacos的配置
server:
  port: 8848
  servlet:
    contextPath: /nacos
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i'
    basedir: ''



